<?php if ( ! defined('ABSPATH') ) {
	exit;
}

/**
 * !! IMPORTANT !!
 *
 * Do not edit this file!
 * To create a new template, simply create a folder in your current theme folder called 'sliced'.
 * You can then copy this file into the 'sliced' folder and edit that copy.
 * This will ensure that your template files are not overwritten if/when you update the Sliced Invoices plugin.
 *
 */




do_action( 'sliced_before_invoice_display' ); ?><!doctype html>
<html <?php language_attributes(); ?>>
<head>
	<meta charset="UTF-8">
	<title><?php wp_title() ?></title>
	<meta charset="<?php bloginfo( 'charset' ); ?>" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="robots" content="noindex,nofollow">

	<?php do_action('sliced_head'); ?>
	<?php do_action('sliced_invoice_head'); ?>
    <button id="clean-pdf-btn" class="no-print" style="padding: 12px 25px; background: #0073aa; color: white; border: none; border-radius: 5px; cursor: pointer; font-weight: bold; margin-bottom: 20px;">
        Rechnung normal als A4 PDF speichern
    </button>

    <script>
        document.getElementById('clean-pdf-btn').addEventListener('click', function() {
            var printStyle = document.createElement('style');
            printStyle.innerHTML = `
        @media print {
            /* Grund-Setup für die Seite */
            @page {
                size: A4 !important;
                margin: 0 !important; /* Wir steuern die Ränder jetzt absolut sicher über das Padding unten */
            }

            /* Blendet Theme-Kopfzeilen, Menüs, Buttons und den Sliced-Invoices {PAGENO} Text aus */
            header:not(.invoice-header), footer:not(.invoice-footer), nav, .site-header, .site-footer, #wpadminbar, .no-print, .print-only {
                display: none !important;
            }

            body, html {
                background: white !important;
                padding: 0 !important;
                margin: 0 !important;
                height: max-content !important;
            }

            /* --- HIER IST DER FIX FÜR DIE RÄNDER --- */
            /* Gibt dem kompletten Rechnungsbereich einen festen Rahmen, der nicht ignoriert werden kann */
            .sliced-invoice, #sliced-invoice-container, .invoice-template, .sliced-wrap {
                width: 100% !important;
                max-width: 100% !important;
                margin: 0 !important;
                /* Oben: 0.5cm, Rechts: 0cm, Unten: 0.5cm, Links: 0cm */
                padding: 0.5cm !important;
                box-sizing: border-box !important; /* Verhindert, dass die Ränder die Seite breiter machen */
                box-shadow: none !important;
            }

            .sliced-upper {
                margin-top: 0 !important;
                padding-top: 10px !important;
            }

            /* Tabellen und Schriften */
            table {
                width: 100% !important;
                font-size: 12px !important;
            }
            body {
                font-size: 12px !important;
                line-height: 1.4 !important;
            }

            /* Logo-Größe radikal verkleinern */
            .invoice-logo img,
            .logo img,
            #logo img,
            header img,
            .sliced-invoice-logo img,
            .sliced-business-logo {
                max-width: 120px !important;
                max-height: 80px !important;
                width: auto !important;
                height: auto !important;
            }

            /* --- Abstände anpassen --- */
            .row.sliced-payments {
                margin-top: 0px !important;
                margin-bottom: 10px !important;
                padding: 10px 30px !important;

                p:last-child {
                    margin: 0 !important
                }
            }

            /* Polsterung der grauen Box: 5px oben/unten, 10px links/rechts */
            .generic, .bank {
                padding: 5px 10px !important;
                margin-bottom: 0px !important;
            }

            .row.sliced-footer {
                margin-top: 0px !important;
                margin-bottom: 0px !important;
            }
            .terms-text {
                margin-bottom: 0px !important;
            }

            htmlpagefooter, .footer-text {
                margin-top: 10px !important;
                margin-bottom: 0 !important;
                padding-top: 0 !important;
                padding-bottom: 0 !important;
            }

            hr {
                margin-top: 0px !important;
                margin-bottom: 0px !important;
            }
        }
    `;

            document.head.appendChild(printStyle);
            window.print();
            setTimeout(function() {
                document.head.removeChild(printStyle);
            }, 1000);
        });
    </script>
</head>

<?php do_action( 'sliced_invoice_before_body' ); ?>

<body class="body sliced-invoice">


	<div class="container sliced-wrap">

	<?php if ( $watermark = sliced_get_invoice_watermark() ) : ?>
		<div class="watermark no-print"><p><?php echo esc_html( $watermark ) ?></p></div>
	<?php endif; ?>

		<!-- ///// Start PDF header -->
		<htmlpageheader name="sliced-pdf-header">

			<div class="row sliced-header">
				<div class="col-xs-12 col-sm-6 sliced-business">
                        <?php sliced_display_business_new(); ?>
                    </div>
                <!--<img class="logo sliced-business-logo" src="https://partycrowd.at/wp-content/uploads/2024/02/aef07ec-300x169.png">-->
				<div class="col-xs-12 col-sm-6 sliced-title">
					<h2><?php echo esc_html( sliced_get_invoice_label() ); ?></h2>
				</div>
			</div><!-- END row -->

		</htmlpageheader>
		<!-- End PDF header ///// -->


		<div class="row sliced-upper">
			<div class="col-xs-12 col-sm-6 sliced-from-address sliced-address">
				<?php sliced_display_from_address_new(); ?>
			</div>

			<div class="col-xs-12 col-sm-5 sliced-details">
				<?php sliced_display_invoice_details_new(); ?>
			</div>
		</div><!-- END row -->


		<div class="row sliced-middle">
			<div class="col-xs-12 col-sm-6 sliced-to-address sliced-address">
				<?php sliced_display_to_address_new(); ?>
			</div>
		</div><!-- END row -->


		<?php if ( sliced_get_invoice_description() ) : ?>

			<div class="row sliced-lower">
				<div class="col-sm-12 sliced-description">
					<?php echo wpautop( sliced_get_invoice_description() ); ?>
				</div>
			</div><!-- END row -->

		<?php endif; ?>


		<div class="row sliced-items">
			<div class="col-sm-12 sliced-line-items">
				<div class="table-responsive">
					<?php sliced_display_line_items_new(); ?>
				</div>
			</div>
		</div>
		<div class="row sliced-items">
			<div class="col-xs-12 col-sm-5 sliced-totals">
				<?php sliced_display_invoice_totals_new(); ?>
			</div>
		</div><!-- END row -->

		<?php if( sliced_is_payment_method( 'generic' ) || sliced_is_payment_method( 'bank' ) ) : ?>
		<div class="row sliced-payments">
			<div class="col-sm-12">
				<?php if( sliced_is_payment_method( 'generic' ) ) : ?>
					<div class="generic"><?php echo wpautop( sliced_get_business_generic_payment() ); ?></div>
				<?php endif; ?>
				<?php if( sliced_is_payment_method( 'bank' ) ) : ?>
					<div class="bank"><?php echo wpautop( sliced_get_business_bank() ); ?></div>
				<?php endif; ?>
			</div>
		</div><!-- END row -->
		<?php endif; ?>

		<!-- ///// Start PDF footer -->
        <htmlpagefooter name="sliced-pdf-footer">
            <div class="row sliced-footer">
                <div class="col-sm-12">
                    <?php
                    // 1. Neue Referenz-Zeile
                    $global_num = get_post_meta( get_the_ID(), '_global_invoice_number', true );
                    if ( $global_num ) {
                        $old_num_format = sliced_get_invoice_prefix() . sliced_get_invoice_number() . sliced_get_invoice_suffix();
                        echo '<p style="text-align: center; margin-bottom: 5px; font-weight: bold;">Rechnungs-Nr. RE-' . esc_html( $global_num ) . ', Referenz: ' . esc_html( $old_num_format ) . '</p>';
                    }

                    // 2. Dynamischer Footer-Text (Website - Email - Telefon)
                    $profile = get_partycrowd_sender_data();

                    $footer_domain = $profile['clean_domain'] ? $profile['clean_domain'] : 'partycrowd.at';
                    $footer_mail   = $profile['mail'] ? $profile['mail'] : 'office@' . $footer_domain;
                    $footer_phone  = $profile['phone']; // Lädt die Fallback-Nummer von oben

                    $dynamic_footer = 'Website: ' . esc_html($footer_domain) . ' &ndash; Email: ' . esc_html($footer_mail) . ' &ndash; Telefon: ' . esc_html($footer_phone);
                    ?>

                    <div class="footer-text" style="text-align: center;">
                        <?php echo $dynamic_footer; ?>
                    </div>

                    <div class="print-only"><?php _e( 'Page', 'sliced-invoices') ?> {PAGENO}/{nbpg}</div>
                </div>
            </div>
        </htmlpagefooter>
        ```
        <!-- End PDF footer ///// -->
    </div> <!-- END sliced-wrap -->

<?php do_action( 'sliced_invoice_footer' ); ?>
<?php do_action( 'sliced_template_footer' ); ?>
</body>

</html>

